### ISSUE TITLE
Bios Auto-Setup

### ISSUE THREAD

**Issue by MichaelHP** [Death259/PiAssist#13]
Identify megaupload link for a tarball of all correct bios files to live. 

identify correct path and filename of all system bios via https://github.com/petrockblog/RetroPie-Setup/wiki/BIOS-setup-for-RetroPie

Tar up said bios and create script
# aquire bios setup tar

wget  download link
# Untar bios files

tar -xvzf filename.tar.gz
# Move files to predetermined file paths

mv biosfilename /bios path

**Comment by Death259** [comment]
I'm not sure if I will be able to do this... legally speaking. I'll look into it some though.

**Comment by Death259** [comment]
Due to legal reasons, I won't be able to fulfill this request.
