### ISSUE TITLE
Auto setup and configure Kodi

### ISSUE THREAD

**Issue by MichaelHP** [Death259/PiAssist#14]
Quick painless script to install kodi and then pipe the correct xml format to es_systems.cfg for kodi to display correctly, possible wget in the correct theme for kodi as well.

**Comment by Death259** [comment]
Looks like this shouldn't be too much work. Here's  the information from [PetRockBlog](https://github.com/petrockblog/RetroPie-Setup/wiki/KODI) for my own future reference.

**Comment by Death259** [comment]
Also, can use the following [blog post](https://weekendengineer.wordpress.com/2014/09/03/installing-xbmc-on-raspberrypi/) to install it.

**Comment by HerbFargus** [comment]
This post also details how to setup kodi 15 with a raspberry pi 2 (Kodi 15 doesn't have the black screen bug though not as many addons are supported yet in the latest  kodi build.) http://blog.petrockblock.com/forums/topic/exiting-kodi-to-emulationstation/#post-99100

**Comment by Death259** [comment]
This is already baked into RetroPie, so i'm going to close this out.
