### ISSUE TITLE
add mame gen xml to fix gamelist.xml issues

### ISSUE THREAD

**Issue by MichaelHP** [Death259/PiAssist#15]
get http://webspace.lenscritic.com/mame/mameGenXml.tar.gz

We'll move it into a new direcotry:

   mkdir genScript
   mv mameGenXml.tar.gz genScript/
   cd genScript/

Expand the contents:

   tar zxvf mameGenXml.tar.gz

Now run it! We'll send the output to a new file called gamelist.xml. You'll need to pass the full path to the roms, the mode (either "mame", "fba", or "console"), and the rom extension ("zip", "nes", etc).

Here's an example for MAME:

   perl mameGenXml.pl -rompath /home/pi/mame4all/roms/ -mode mame -extension zip > gamelist.xml

Here's an example for FBA:

   perl mameGenXml.pl -rompath /home/pi/fba/roms/ -mode fba -extension zip > gamelist.xml

and finally an example for console:

   perl mameGenXml.pl -rompath /home/pi/roms/nes/ -mode console -extension nes > gamelist.xml

Now you just need to move the gamelist.xml into your roms directory. Note: THIS WILL OVERWRITE ANY EXISTING GAMELIST.XML, so if you already have one please back it up first:

   mv gamelist.xml /home/pi/mame4all/roms

change for individual user and automate running gamelist.xml fix for all platforms

**Comment by Death259** [comment]
This functionality should already be included with the SSELPH scraper.
