### ISSUE TITLE
Bluetooth Controller - Persistent Connection

### ISSUE THREAD

**Issue by craigerskine** [Death259/PiAssist#16]
This tool is awesome for connecting my NES30 pro, however, how do I allow my controller to be a "trusted" device? When I turn off the controller after playing and then come back to play later the controller does not connect unless I run your connection script again.

Is there a cron job or some file I can edit to allow it to be a trusted device?

**Comment by Death259** [comment]
I don't believe the NES30 Pro supports automatic connections quite yet. That could likely come in a firmware update. I've got both a NES30 and a NES30 Pro. My NES30 connects automatically, but my NES30 Pro does not. I've updated the firmware on my NES30, so I'm hoping that will come in a firmware update for the NES30 Pro. You could setup a cron job to attempt to connect every so often, but I'm not quite sure what that will do if you are in the middle of using it, when it tries to run again. 

If you want to do that, you will need to get the MAC address of your NES30 Pro. To do that, you can  either run the script and get it from there, or run `hcitool scan` to get a listing of devices including the MAC address. Then the command to connect to the controller is `bluez-test-input connect MACADDRESS`. You just simply need to replace MACADDRESS with the one from your device. Then you will have to set that up as a cron task. I haven't done that in a while, so I'm not 100% on what you have to do, but you can use the [raspberrypi.org documentation](https://www.raspberrypi.org/documentation/linux/usage/cron.md), which seems fairly thorough.

I'll leave this open as an issue and then if I manage to fix it with my NES30 Pro, I will post the results.

**Comment by craigerskine** [comment]
Thanks for the info, I had my pro auto connecting to RetroPie 3.0 beta 2 (finished Mega Man and made it to level 3 boss in Blaster Master for the past few days). I just updated to beta 3 today and now my controller does not auto connect. The sudo bluez-simple-agent hci0 XX:XX:XX:XX:XX:XX command throws an error on line 158 although the connect command does re-connect.

I'll try using my SNES30 or NES30 in its stead. Again, thanks for the awesome tool.

**Comment by Death259** [comment]
No problem, glad I could help! I tend to be busy during the week, but I'll try to hash out new features and bug fixes throughout the weekend. I've got some great ideas and suggestions in the pipeline, so I'm hoping I can make this tool even more useful.

If you need to schedule a cron job, I took the liberty of [creating the bash script](http://www.mediafire.com/view/5f5708jr6ab7krl/ConnectToNES30Pro.sh) that you can schedule. You'll have to modify it to have your mac address, but I believe it should work.

**Comment by Death259** [comment]
On a different note, would you mind sharing your SNES30 config? I'm trying to compile various configs to help others with that whole process. I believe as of version 3, they are now stored in `/opt/retropie/emulators/retroarch`.

**Comment by craigerskine** [comment]
I haven't been able to make the NES30 or SNES30 controllers work properly yet. They pair and connect, but when I run the Input Config in ES the D-PADs do not work right. I think I might have to connect them via B + Start to force keyboard mode. After I do that I'll send my Configs.

Also, I found some simple steps to create a cron job to auto connect every minute:

Via command line type each line exactly and hit return. Replace 'XX:'... with device MAC address:

```
crontab -e
* * * * * sudo bluez-test-input connect XX:XX:XX:XX:XX:XX > /dev/null 2>&1
```

CTRL + X to exit.

**Comment by Death259** [comment]
What happens if it tries to connect while you are using it?

Also, good work on the crontab, i had forgotten to add sudo and send the output to /dev/null.

**Comment by craigerskine** [comment]
I'm sure the cron job could be optimized. I'm relatively new to the syntax and I'm not sure how to do if statements. Probably set up a .sh and do ifs in there. Not sure how to test to see if it's already connected.

**Comment by Death259** [comment]
Yeah, you could definitely do an if statement around it. Something like

```
if [ "$(bluez-test-device list)" == "" ] ; then
    sudo bluez-test-input connect XX:XX:XX:XX:XX:XX > /dev/null 2>&1 &
fi
```

Basically, you're just checking if there are any devices connected via bluetooth, and if there are not then you will try to connect to the one specified. You could get more specific and have it check for if the connected device list contains the specific device's mac address, but that will take a little more work.

**Comment by Death259** [comment]
Doing a little more thinking, checking for the specific MAC address I don't think would be too bad. I think you can do the following (haven't tested):

```
if [[ "$(hcitool con)" != *"XX:XX:XX:XX:XX:XX"* ]]
then
    sudo bluez-test-input connect XX:XX:XX:XX:XX:XX > /dev/null 2>&1 &
fi
```

Edit: I messed up on the logic. It needed to be `!=` and not `==` since if the mac address it not in the list of connected devices, then we want to connect to it. Also used the wrong command. I had it look for registered devices when instead it needed to look at currently connected devices.

**Comment by craigerskine** [comment]
My cron was working but it was acting kind of weird in some instances. I think it was the connect trying over and over. I'm going to try your solution now and see if I can get it working.

Here are the configs for my SNES and SFC controllers:

8BitdoSNES30GamePad.cfg || 8BitdoSFC30GamePad.cfg

```
input_device = "8Bitdo SNES30 GamePad"
input_driver = "udev"
input_b_btn = "12"
input_y_btn = "15"
input_select_btn = "21"
input_start_btn = "22"
input_up_btn = "0"
input_down_btn = "5"
input_left_btn = "2"
input_right_btn = "3"
input_a_btn = "11"
input_x_btn = "14"
input_l_btn = "17"
input_r_btn = "18"
input_enable_hotkey_btn = "21"
input_exit_emulator_btn = "22"
input_menu_toggle_btn = "14"
input_load_state_btn = "17"
input_save_state_btn = "18"
input_reset_btn = "12"
input_state_slot_increase_btn = "3"
input_state_slot_decrease_btn = "2"
```

**Comment by craigerskine** [comment]
This is what I created to make the cron thing work...
- I made a file called controller-connect.sh in my home directory. The contains this:

```
if [ "$(hcitool con)" != *"XX:XX:XX:XX:XX:XX"* ]
then
  sudo bluez-test-input connect XX:XX:XX:XX:XX:XX
fi
```
- I typed contab -e and added the following:

```
* * * * * sudo /home/pi/controller-connect.sh > /dev/null 2>&1
```

For some reason the double [[ was erroring out. When I changed it to a single [ it worked.

Thank you for your help and getting me on the right track for pairing my NES30 pro controller. I really appreciate your hard work.

**Comment by Death259** [comment]
I updated my RetroPie to beta 4 and updated the firmware on my NES30 Pro and it will now reconnect automatically. I can turn on my Pi and then turn on my controller and it will connect without having to use PiAssist. Give it another shot with beta 4 and let me know if the problem still persists.

**Comment by craigerskine** [comment]
Yes, it does work more reliably in Beta 4 now. If only the NES30 and SNES30 could reconnect as well. I ended up going with a Dualshock 4 in the end. I used your script to do the initial connect and added a few lines to my local.rc file to get it to reconnect every time without fail.
