### ISSUE TITLE
Feature request: "New" Tag on newly added roms

### ISSUE THREAD

**Issue by ghost** [Death259/PiAssist#21]
Exactly the title. When a new ROM is added, I would love there to be a "new" tag that appears next to the title and/or emulator. Perhaps by going off the "Last played" metadata within RetroPie?

**Comment by Death259** [comment]
Are you wanting this to be displayed within Emulation Station?

**Comment by ghost** [comment]
Sorry! Yes. Do-able?

**Comment by Death259** [comment]
It might be do-able, but not by the likes of me, sorry. That change would need to be made within the Emulation Station code. You might try suggesting it on [their github](https://github.com/Aloshi/EmulationStation). I like the idea, it's just not something I could do.
