### ISSUE TITLE
Using Scraper from PiAssist menu when using external hard drive does not work

### ISSUE THREAD

**Issue by MichaelHP** [Death259/PiAssist#24]
Utilizing Scraper from sudo at the command line
Reports roms scraped and no information is downloaded

I am utilizing all the directories   in my /media/usb0 folder which is the most common mount point for an ext hard drive all the rom folders are then the same as they were. 

Error reporting is very quick i saw a message about cannot access a directory but cant find a tmp log to get better information

ALso note the user pi has write and read access to the /media/usb0 folder as I have already configured that.

**Comment by Death259** [comment]
I will look into this. Thanks for submitting a bug. I haven't setup and
external hard drives myself, but I can likely do so to verify a fix.

**Comment by Death259** [comment]
As of commit f39cac6de1c84431f2f3fa8f869b2f6db34e5ba8 this issue should be resolved. If you don't mind, give it another shot and let me know your results.

**Comment by Death259** [comment]
The scraper is built-in to the RetroPie source and should be able to accommodate this now.
