### ISSUE TITLE
Splashscreen Directory Change

### ISSUE THREAD

**Issue by HerbFargus** [Death259/PiAssist#27]
As of the RetroPie 3.0 image, the splashscreens are now in `/opt/retropie/supplementary/splashscreen`

**Comment by Death259** [comment]
Thanks, I will make the necessary change. I will try to still make it backwards compatible if possible.

**Comment by HerbFargus** [comment]
Likelihood is they'll change again in the future to be provided with the configs with samba shares... But my guess is they'll be in their current folder for the foreseeable future

**Comment by Death259** [comment]
As of commit ede04aac2741a9a48501a72aff00db9c66483b18 this should now be accommodated for. It will check and see if the new directory exists and if so will use it.
