### ISSUE TITLE
Using Sselph latest release

### ISSUE THREAD

**Issue by sreisig1** [Death259/PiAssist#32]
Does the built in Sselph scraper use the latest release?

**Comment by Death259** [comment]
I haven't updated this thing in forever, so it may not work with the latest version of RetroPie. It does, however, grab the latest version of the sselph scraper every time it runs. Your best bet though, if you are wanting to use the sselph scraper, is to probably use the one built into the retropie setup script.

**Comment by sreisig1** [comment]
Thanks. Had I known it had one built in now I would have used it. Oh well. Seems to be running fine, we'll see soon. Does it use thumbnails by default too? Should have checked all that before running it. Been running it since last night, almost done.

**Comment by Death259** [comment]
I wanna say it grabs the full image, and not thumbnails.

**Comment by sreisig1** [comment]
Damn alright thanks. Wonder how much space it's taking up, have over 4500 games 😁
