### ISSUE TITLE
Add Searching For Files

### ISSUE THREAD

**Issue by Death259** [Death259/PiAssist#6]
Add the ability to search for files.

Ex. sudo find . -name *InputAutoConfig.ini*

**Comment by MichaelHP** [comment]
suggest locate as the command versus find.

**Comment by Death259** [comment]
Search functionality has been added in commit 9c7834f2da94c730712b0744b7ab478f8d7ebd8e. I stuck with find versus locate, simply because I was already familiar with it. I plan on looking at Locate in the future though.

**Comment by MichaelHP** [comment]
Have not yet been able to test,
But does the output of this visually represent all known locations if there are multiple copies of the same filename?

**Comment by Death259** [comment]
It should show you all locations where the filename matches. It's rudimentary in the sense that it just displays the results in the CLI. I will try to make the results display in the dialog menus in the future.

**Comment by Death259** [comment]
I've made the results now display in a whiptail menu, so it should be more appealing and easier to read.
